def generate_username(birth_year, full_name):
    first_name = full_name.split(" ")[0].lower()
    birth_year_trunc= birth_year[2:]
    username = first_name + birth_year_trunc
    return username

def main():
    full_name = input("Enter your full name: ")
    birth_year = input("Enter your birth year: ")
    username = generate_username(birth_year, full_name)
    print(f"Here is your autogenerated username: {username}")

main()